language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python-dev python-xlib python-tk
- curl http://heanet.dl.sourceforge.net/project/python-xlib/python-xlib/0.15rc1/python-xlib-0.15rc1.tar.gz -o /tmp/python-xlib-0.15rc1.tar.gz
- tar -zxvf /tmp/python-xlib-0.15rc1.tar.gz
- pip install --upgrade pip
- pip install /tmp/python-xlib-0.15rc1.tar.gz
- pip install pillow
- pip install pyautogui
- pip install robotframework
script:
- python tests/utest/run_tests.py
notifications:
  email:
    recipients:
    - tatu.kairi@eficode.com
    - markus.suonto@eficode.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      - secure: "gY5UD57i1QV4X6JLaFDZoAfzgx5Li1frmnI0zfOCCYUO/UJm1WqKlWQSvp5W990dc1LV3YzRNihFCHYZ0YKsOKogd1DvIIV6rxJbn3KX8HB4EoVTqM47gqs15shgFkVohFUQ+Re8xB92Ou4zdED7tTrmZQsyFxk977Gighgj4gYXvi5r9arqAew35HZh0oZFpQMJJDKE6KOwCjw3w35NHwbsaECIamsWzE4c7/p0A3pVGnSvBor8kS8rqivoMo9cj7dACLeaWL8zftGxne9qyUColeH2jGQp8bgR30B23XrZfnmKFV6kk2oosQSLL65AQCM4nbgwXH/WZvUloWc9I+hGfZ7WOTtDaPVqn+CSprQ6l2nMX3n3BpyY4OY8XyCw97wR11vyofoRu17E9hSSgrtKmsRS04BRia2hl0+UCsPXwW3YD/fh+yUO1VmSN0gSyg9KmrNG6se+Ed1uit6Ujj1xBIG0CLkHWToYwL0XqCAuOog6F5vq78SMBLgWCRP8AvTbIXpxokIRY+JMq9zp5aHL3WkrMPyf/U3y/VWlLLOYnaW2sZmMCJnVuKTTC+dC8EznVrJ/meHBeseHH2W/O867NoEJWxNNanALv29Boncr87wQ/NlsrDq81DGT9g2WF8S4XVgVz0GxUxzVlYE9hYgWwP1MR6eUliEvoXUK3P0="
      - secure: "FRjyZH8vYigv/k2C6hQA/PaJdbLk2+wsFL0TRvdjpgv9nPQAV68h6StvDyIepJ84iRrnHU1nPNi4eA2qdebvfrIV9IWi/QYgRaWDTgWjoVGjU4Pj+XGEUoonLvuIv0xmBTNTm6sozsNS2l64xwyGGQflILgSBr82UIOgJlYPDIpGn31T4AnuZGQ64bSQu7Mtkts+xnivO1taTw2JkfaYlc4ZyHnZkhwW4sXHlUF7eHcjjiE4SBr6c2Fkl6B58ZQHFrmxb+n0FDwur0dDgqIHFw+OrlFcA79uMPLAZ/OiSMJ/lTL3kuuhvB7W2q1t6/buY0ypY7rWB9Ho8d7qi3V1UaT9tDjUxObhzyu6J+RaJcpnMiqcWUeU+KypegRfRcVclfLvGNv69wBBRfSviWW4UjnzjNiwi2yMlLbqhTSQJNCeL5BAczSsXJ9S/tSObdcu23OKW1HWIfnZALXrStQd2d/yxZrq8RUU+GnKo8Kk3wKU3OFUK1d+Gdn+NsDFr2GcUsdHy29Aw7OmirgF3Gflxi2ABoJIsPr9y/1buWloBaA0TNW7cW00Zx/AQldMMccvFnmafVb7xjTP7NMAxaT8bfiWSfhEr9XXKVSiiMu0Xim81FDcV6NEwXbk09RAGtI1WEky0pAJ5df7oCRMtwAwGyVooCF2skBUKUZRtQ4vGyE="
      - secure: "Q9Zr8s6QbdspqwBrX4PK17TEi6HiJkSphTDF3ulMwAm8j/qoOXL9FYbeWALbfdqpMfCSQb6fJK+ZYBrzm+ISqTtsDS7IjXfuY+ZLQKfKmh2dt81ZAEncHjiNqXXV7KC2T/tyEPml2HOHAweHE/a+Plm6wztc5Z4hJbEnTOc2tOHBeq2oIXNW8syNYLdbqVPB6tXe7/pII/pwUxcoSG5qzTvlExVb3k613PX4M9r2yBt9sgkUM1wcoE/eTshHNsppdn4OCZYsqROoIa1jNCqi5O/+aX6qhXqNNDTW0z9NfWuxqo/XLJXZpgKMqB6fYwDKiWCmw1bKxcXGiu8utcy1iqkvGg9tbnnUJAyH7vZFp/DILfrZzdp0vP9SA34xyD/yVxXcVMMW+eQ1IZsFZAYKEqj+s2Hzo8wyvPVxKkBKfcwk/9hwInGWFre78Foc3Yy2y0d19haERdeyg/UPlo0A+BIThbrZaY0YoG/JoRGR5tCOCKsRQlFxV+3KF14oAZkHJjEtWW6vjHxvMYV4ks1Nkh+VZvC52ec6lqQyoBp1HfSmVPz2OpR8v4MFR4NHseciJ4oZ7uRRZ+TvN7GADnNiHYsdQ4zWXpVQMynbd0lCf4ymGDWzDZ54MsqIa6XnZLmG5xkmi4aXXJcSWBhAvjUGk0j1q+Z1V1vAdpCfwzetyeI="
    on_success: change
    on_failure: always
    on_start: never
    on_pull_requests: false